### PR TITLE
add my profile

### PR DESCRIPTION
**Pull request by sonilaia**

### CODE REVIEW

**Comment by mmuhamadamirzaidi** [comment]
Please follow the format as stated in the hacktober-2020.html file @nitinshukla413 . Thanks.

**Comment by mmuhamadamirzaidi** [comment]
Which country you are, @sonilaia ? I will add it manually to you.

**Comment by sonilaia** [comment]
Hi Mmuhamadamirzaidi/Hacktoberfest

I'm from indonesia,
Thanks

**Comment by mmuhamadamirzaidi** [comment]
Great @sonilaia. Will add you directly to the list. And I will close this issue once it is done 👍

**Comment by sonilaia** [comment]
Thanks

**Comment by mmuhamadamirzaidi** [comment]
**Don't forget to give a STAR for this repository :D** @sonilaia

**Pull request closed without merging**
