### PR TITLE
Zubair-12

### PR DESCRIPTION
**Pull request by Zubair-12**
Hi @mmuhamadamirzaidi  Please Review this PR. Thanks!

### CODE REVIEW

**Comment by mmuhamadamirzaidi** [comment]
Please left the original copy of structure, copy and paste, after that you can add your details. Also put the link for href and the text. Thanks @Zubair-12

**Comment by Zubair-12** [comment]
OK sorry I am beginner, that's why it happened.

**Comment by Zubair-12** [comment]
By the way I am going to do this, that you have said @mmuhamadamirzaidi Thanks.

**Comment by mmuhamadamirzaidi** [comment]
I have a fix it already. Great work by the way @Zubair-12

**Comment by Zubair-12** [comment]
Thanks brother @mmuhamadamirzaidi !

**Comment by mmuhamadamirzaidi** [comment]
My pleasure :D

**Comment by mmuhamadamirzaidi** [comment]
**Don't forget to give a STAR for this repository :D** @Zubair-12

**Comment by Zubair-12** [comment]
Yes ofcourse I have already done this.

**Comment by mmuhamadamirzaidi** [comment]
Thanks @Zubair-12 :D

**Pull request merged**
