### PR TITLE
GoelSahab

### PR DESCRIPTION
**Pull request by GoelSahab**

### CODE REVIEW

**Comment by mmuhamadamirzaidi** [comment]
Do you have any LinkedIn @GoelSahab ? Go and create one. It will help you a lot :D

**Comment by GoelSahab** [comment]
But now i am in 11th so i plan to make it in future

**Comment by GoelSahab** [comment]
Pls merge

**Comment by mmuhamadamirzaidi** [comment]
Oh great. Coding at the young age. More success for you in the future. Before I merge, please update your Github link also for the text 'Github Link'. You may refer other details for more understanding :D. Thanks @GoelSahab

**Comment by GoelSahab** [comment]
I provided GitHub link in it

**Comment by GoelSahab** [comment]
Sir i dont know how to push in same branch

**Comment by mmuhamadamirzaidi** [comment]
Done merge you details @GoelSahab . Great work! :D

**Comment by mmuhamadamirzaidi** [comment]
**Don't forget to give a STAR for this repository :D** @GoelSahab

**Pull request merged**
