### PR TITLE
Update hacktoberfest-2020.html

### PR DESCRIPTION
**Pull request by vaaleyard**

### CODE REVIEW

**Comment by mmuhamadamirzaidi** [comment]
Please update the href and also fill in the country. Thanks @Valeyard1 :D

**Comment by vaaleyard** [comment]
Is it good now? I updated the country

**Comment by mmuhamadamirzaidi** [comment]
Great work @Valeyard1 :D

**Comment by mmuhamadamirzaidi** [comment]
**Don't forget to give a STAR for this repository :D** @Valeyard1

**Comment by vaaleyard** [comment]
I'm sorry, but don't you have to add the label `hacktoberfest-accepted` to count this PR?

**Comment by mmuhamadamirzaidi** [comment]
Hi @Valeyard1, yes. Will add it tonight for all the successful PR made :D

**Pull request merged**
